### ISSUE TITLE
No way to post a description to a Invoice Refund

### ISSUE THREAD

**Issue by NaughtyMC** [recurly/recurly-client-net#136]
When calling Invoice.RefundAmount() to do a partial refund of an invoice, there is no way to pass in a description.

We really like that functionality in the Adjustment.Create() method; is there any way to bring that functionality to the refund feature?

**Comment by 1TheMuffinMan** [comment]
@NaughtyMC Unfortunately there's no way for us to accomplish this through the .NET client library as the corresponding API endpoint doesn't support it. Your best bet would be to contact Recurly customer support directly and request this feature so that it can be built into the API itself.

Here's the invoice refund documentation that I'm referencing. https://dev.recurly.com/docs/open-amount-refunds
