### ISSUE TITLE
Subscription.GetHashCode() throw exception when uuid is null.

### ISSUE THREAD

**Issue by nguyenphu1012** [recurly/recurly-client-net#153]
Hi,

When I tried to retrieve a subscription with pending subscription, the pending subscription will have uuid null, which will cause exception when you call GetHashCode(); actually is called by AutoMapper.

Can someone fix that?

Thanks,

**Comment by bhelx** [comment]
@nguyenphu1012 Thanks a lot for reporting this. I will try to reproduce it first thing in the morning. If it is a bug, it should be a simple fix.

**Comment by MuffinMan10110** [comment]
I believe I fixed this same issue on a different object a while ago. GetHashCode() was overridden to get the hash code of the uuid and was sometimes null, causing an issue. I'll see if I can find it.

**Comment by bhelx** [comment]
@nguyenphu1012 Is this still a problem? I was never able to reproduce

**Comment by MuffinMan10110** [comment]
@bhelx Pretty much any code that is overriding GetHashCode() should be removed. There's no reason to override it and only serves to create hard to reproduce issues. As stated by @nguyenphu1012 you should be able to reproduce this with Automapper when mapping from one type to another. I'd be happy to change this if you are okay with it.

**Comment by 1TheMuffinMan** [comment]
It looks like the creator of the library intended for two recurly objects to be equal if their Id's were the same, in this case Uuid. I believe you could essentially take two completely different subscription objects with the same id, compare them, and determine that they are the same. So I believe the solution in this case is to check if the object is null first so that all null objects would get the same hashcode. I can start on this.
