### ISSUE TITLE
Setting Api Keys without using Config Files

### ISSUE THREAD

**Issue by BenjaminGibbs** [recurly/recurly-client-net#160]
Is it possible to use the library without using the config file?

Using a config file is out of the question due how our deployment works, so I am looking for another way to inject the API key, but can't seem to find one.

Ideally I would like something like.
recurly.settings.setconfig(apiKey, subdomain);

Something like that might be included but I am missing if so.

**Comment by MuffinMan10110** [comment]
@BenjaminGibbs No, the library is not designed to configure settings without the web/app.config. You'll have to use reflection to do it at runtime if that's what you want to do. I've provided an example of how to do this in a previous issue: https://github.com/recurly/recurly-client-net/issues/148

The reason the library relies on the web/app.config is because it's a standardized method of setting configuration. The best way to do build and release management is to build once using your dev credentials and allow your release management software such as Octopus Deploy to swap out all of your dev credentials with staging or production values. Environment dependent or production values should never ever be hardcoded in an application. If you'd like to discuss some ways to improve your build process I'd be happy to share my thoughts.

**Comment by BenjaminGibbs** [comment]
@MuffinMan10110 Thanks for your comment, we are using Visual Studio online with release management currently, which picks up builds off git commits.

We have different sets of keys\settings for our dev\testing\beta\live etc... which depending on the build settings in release management switch in the correct set of keys.

But we are using Azure Cloud Services, and do this with the service configuration files (CloudConfigurationManager), not in the .config files.

Happy to consider another approach if needed.

**Comment by MuffinMan10110** [comment]
This might help http://blog.mattmcloughlin.com/how-to-use-the-cloudconfigurationmanager-to-automatically-switch-app-settings/

It really comes down to a difference in approach. One approach keeps environment awareness out of the application by allowing the release management system to determine which set of credentials should go into the app and the other approach allows the app to know what environment it is in and request a credential set from some other source.

With frameworks like Service Fabric it might make it more legitimate to set the configuration at elsewhere since Service Fabric doesn't rely on web or app.config to access settings.

Based on what you've described about your process and reflecting on workflow for Service Fabric I think making the config more flexible is legitimate.

If you would like to be able to update the config settings programmatically at runtime feel free to fork the repository, add a test for it and submit a pull request.

**Comment by BenjaminGibbs** [comment]
I am going away for the week today but will look at adding something when I get back. - Sound okay?

**Comment by MuffinMan10110** [comment]
@BenjaminGibbs Sure, no problem.

**Comment by BenjaminGibbs** [comment]
I have started on this and submitted a pull request for review. #162

**Comment by BenjaminGibbs** [comment]
This issue can be closed now as it has been merged in to the repo with #162
