### ISSUE TITLE
Multiples API Keys and multithreading

### ISSUE THREAD

**Issue by jvalladolid** [recurly/recurly-client-net#189]
Hi.
I'm using the solution build here #162 to be able to connect to the two Recurly Accounts we use in our solution. Let me explain a bit the use case to understand the error I'm facing to.
As I have just said, we have two Recurly Accounts in PRO to invoice our customers. The customers's subscriptions are created in one account or another depending on the InvoiceTerritoryId we have. For example, Our account in EUR to invoice users from Europe and our account in USA to invoice the rest of the world. So depending on the InvoiceTerritory defined for a customer, I change the Settings of the Recurly Client before making the request. Something like this:

`ConfigureClient(territoryId);`
`Subscription` subscription = Subscriptions.Get("XXXXXXX");`

Where ConfigureClient() is setting the configuration doing something like

`SettingsManager.Initialize(apiKey, subdomain, pageSize: pageSize);`

In a multithread environment, when the service is processing a request that needs to recover the information of the Subscription from the Europe's Account at the same time that another request to the USA's Account, one of them fails because the subsctiption doesn't exist, due to the setting of the client has been changed.
How could I manage different instances of the Recurly Client to use one or another depending on where the subscription of the customer is?

**Comment by bhelx** [comment]
Hi @jvalladolid 

If I'm not mistaken, that PR was not really meant to make this library work with with having configuration on two separate threads. It was meant to make the library configurable with dynamically loaded settings.

There is not a supported way to use this library with multiple configs but I would be open to any changes you need to make to get us there. One possible way could be to have a config override that is scoped to only the thread you are on? I'm not really sure what the recommended way forward for something like this would be in a .NET application.

Perhaps @MuffinMan10110 has an opinion on it?

**Comment by MuffinMan10110** [comment]
It's going to be interesting trying to figure out a way to bend the sdk in this direction. As @bhelx mentioned the library was designed as a singleton. If you look at the source for `Account.Get` you'll see that it calls `Client.Instance`. I think if we had to start over it would have been a good idea to put all of the methods in a RecurlyClient class where you could just say `new RecurlyClient(configOptions)` or pass null to that constructor for it to pull it from the web/app.config automatically. This way you could pay in a different instance using dependency injection.

Off the top of my head two things I could think of are to fork the library and make the necessary hacks in order to get it working for your use case (such as modifying Client.Instance to pass back a new instance instead of a singleton) or perhaps you can use a c# lock statement to block access to other threads until the current thread is finished. Both are not ideal solutions, but may be your only option.

**Comment by jvalladolid** [comment]
Hi @MuffinMan10110 
Yeah, That's the idea I missed when I took a deeply look into the client :-(. The dependency injection is the solution I was thinking on, definitely. Probably, I'll try to implement it. Anyway if you do it, let me know, please. Thanks!!

**Comment by MuffinMan10110** [comment]
@jvalladolid Good luck!

If it ever happens it will be another nuget package in order to maintain backwards compatibility so keep an eye out in the future.

@bhelx can we close this?

**Comment by 1TheMuffinMan** [comment]
@jvalladolid I hope you were able to work around this limitation. We looked into this briefly and determined that it would be a large change in order to accomplish right now. I think it's a good idea to move the library away from a singleton to something like `_instanceOfAClient.GetAccount(1)` at some point though. In the meantime I am going to close this, but let me know if you you'd like to bounce any ideas off of me about it and please feel free to continue suggesting improvements to the library. We're always looking for ways to improve it.

**Comment by jvalladolid** [comment]
Yeah @1TheMuffinMan . We did a work around implementing a mutex in the pieces of code involved, so inside each critical section we configure the client using the desired account and call to the API to get the information needed. That is enough at the moment, but we included in our backlog a technical story to move the client to a version that breaks the singleton pattern used now.
I cannot promise now when it'll be ready, but we'll start in a month probably. It's not really a priority for us now, but we want to do it to be able to have better performance in the future and to collaborate in this project ;-)
