### ISSUE TITLE
RecurlyList -> RemoveAll

### ISSUE THREAD

**Issue by PashaSk** [recurly/recurly-client-net#380]
Is there any reason why you are keeping RemoveAll method of RecurlyList internal? 
https://github.com/recurly/recurly-client-net/blob/master/Library/List/RecurlyList.cs#L172

We have a scenario where we need to remove addons from SubscriptionAddOnList with Quantity == 0. However, we can't do it in clear way:
`addons.RemoveAll(a => a.Quantity == 0);`

**Comment by aaron-suarez** [comment]
I don't see any uses of `RemoveAll` internally, the only thing that comes up in a search is the declaration of the method. There may have been plans for it, but if so, it was never actually implemented.

I'll have to look into the implications of making it public, but I don't see any immediate issues with it. Feel free to open a PR and I'll be happy to review it.

**Comment by bhelx** [comment]
The history behind it is a little mysterious: https://github.com/recurly/recurly-client-net/commit/f7742a99776dc67e12e8a069f4e50a658adcafc3

It almost appears as if they were meant to be public.

**Comment by PashaSk** [comment]
What about other List methods? e.g.
internal bool Remove(T item);
internal void Sort();
internal void Sort(Comparison<T> comparison);
internal T[] ToArray();
internal void Reverse(int index, int count);

Could we made them public?

**Comment by aaron-suarez** [comment]
They seem like they would be useful as public. And I agree, it seems like they were added in for the tests, but it didn't occur to the original author that users might find these methods useful too. Who knows. If you open a PR with all of those methods public, I would be fine with that.

**Comment by bhelx** [comment]
Let's be selective about which ones we open if possible. It's risky because `RecurlyList<T>` is used for pageable lists as well: https://github.com/recurly/recurly-client-net/blob/master/Library/List/AccountList.cs#L5

Ideally I'd say these need to be two different classes. Like, suppose we have some other kind of `editable` list that we extend on top of `RecurlyList<T>` that exposes the methods. Having said that, I could foresee the touch-points to make that change risky as well. I'm open to making them public if we are selective and consider the consequences on the pagination lists. I can't see a case for needing to Remove an item mid-pagination for instance, but could foresee that causing a problem.

**Comment by bhelx** [comment]
Also keep in mind that exposing methods like `Sort` on the pageable lists might also be confusing to the programmer since they don't actually apply any kind of sorting to the server request.

**Comment by bhelx** [comment]
One compromise might be to just expose them in the place they are needed: https://github.com/recurly/recurly-client-net/blob/master/Library/List/SubscriptionAddOnList.cs
still, open to other suggestions.

**Comment by aaron-suarez** [comment]
Closing this out due to lack of activity. @PashaSk If you would still like to open a PR, please feel free. If you do, I think it would be wise to take @bhelx's suggestion of only exposing the specific methods you need in the places they're needed. Thanks!
