### ISSUE TITLE
IHttpClientFactory in V3

### ISSUE THREAD

**Issue by dmcweeney** [recurly/recurly-client-net#404]
Folks,

Wondering are ye planning to use the new IHttpClientFactory features of Asp.Net Core 2.1 in the V3 refactoring work?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2

Thanks

Donal

**Comment by bhelx** [comment]
Thanks for pointing this out. This is a new concept to me so I'll need to do some research. I'm a little hesitant about the idea of letting the programmer control the HTTP layer directly. Although I can see the power in that, my concerns are around compatibility and security.

Did you have any thoughts or opinions about how this could be utilized? Looking forward to doing some more research here.

**Comment by dmcweeney** [comment]
IMO its more about empowering the developer with the flexibility this approach offers, and of course the benefits that it brings. I don't see there been a security issue as one could always write their own calls against the Recurly rest api services.

I think the underlying problem would be the fact that ye are using RestSharp at the moment, and if RestSharp does not support the IHttpClientFactory approach (which it does not appear to) then you would have to refactor all those api calls.

**Comment by bhelx** [comment]
> IMO its more about empowering the developer with the flexibility this approach offers, and of course the benefits that it brings.

I agree with that part. I see the value in it.

> I don't see there been a security issue as one could always write their own calls against the Recurly rest api services.

This is true. However, if someone chooses to write their own version of this library, all support and liability of their dotnet code falls onto them. Since we created this library and it runs in our customer's data-centers, we feel like we have a much higher responsibility to make sure that it's secure, performant, and clear to upgrade. The trade-off is often a loss in some control on the programmer's part. We do feel like this trade-off is a key part of our value proposition though. For instance, you could accept credit cards yourself but our customers cede that control to us so they don't have to shoulder the full burden of security and PCI liability. We see these libraries as an extension of that promise.

> I think the underlying problem would be the fact that ye are using RestSharp at the moment, and if RestSharp does not support the IHttpClientFactory approach (which it does not appear to) then you would have to refactor all those api calls.

I do wish to eventually replace with RestSharp with something more standard. I tried to write the library is such a way that it could be replaced when the time comes.

I'm closing this for now since I'm not sure of a way forward. I think we will re-examine it when we replace RestSharp. For the time being, if there is some level of control you feel like the library is lacking, please let me know I can address those problems individually. I definitely think there are some areas where we could safely allow more control of the HTTP level, but my compatibility concern still remains. We would need to design those features as an explicit interface that we can support forever.
