### ISSUE TITLE
merchant reported removal of all subscription add ons defunct

### ISSUE THREAD

**Issue by whiteotter** [recurly/recurly-client-net#52]
"The RemoveAt() call is a method on the .NET List<T> object and thus runs no functional code against Recurly. It simply removes the item from the list.

The issue is not removing a single SubscriptionAddOn but rather manifests when all addOns for a subscription are removed. As long as there is at least 1, the code functions as expected. When all addOns are removed, the subscription_add_ons XML element is not written to the request by the C# client and it appears that the Recurly API takes no action when this collection parent element is not found. "

**Comment by MuffinMan10110** [comment]
@whiteotter If I understand your issue correctly what you're saying is that when you remove all of the subscription AddOns using `Subscription.AddOns.RemoveAll()` or `.RemoveAt(...)`The `Update()` method doesn't actually remove the add ons because the `subscription_add_ons` XML is not being written for an empty list?

**Comment by bhelx** [comment]
It would be good if we had some code on this issue

**Comment by whiteotter** [comment]
This issue was quoted directly from a merchant communication. I will reach out to that merchant and encourage them to weigh in here. Thanks.

**Comment by bhelx** [comment]
Thanks, we'll leave open for now

**Comment by 1TheMuffinMan** [comment]
@whiteotter If you do hear from your client on this and can provide additional information please let us know. Closing this for now.
