### ISSUE TITLE
No way to change a plan code

### ISSUE THREAD

**Issue by MrHenkey** [recurly/recurly-client-net#99]
It seems that it is not possible to update a plan code. When Plan.Update() is called, the client create PUT request to /plans/:plan_code where ":plan_code" is the new (changed) value. Since there is no plan with that code at the time when Update() is called, NotFoundException is thrown.

Maybe, method override like Update(string planCode) could be a solution here.

**Comment by bhelx** [comment]
@MrHenkey our API does not allow a plan code to be updated. plan_code is used as a unique identifier for the resource so allowing you to change it would break RESTful practices. You may, however, change the plan name or you can create a new plan with a new plan_code.

Please feel free to re-open if you don' think this problem was resolved for you.
